"""
rf_exporter.py - Robot Framework / RPA.Windows locator exporter.

Generates Robot Framework keywords, locator variables, and full .robot
file snippets that use the RPA.Windows library syntax.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from src.core.uia_wrapper import ElementInfo
from src.export.locator_strategy import build_locator_strategies, best_locator

if TYPE_CHECKING:
    from src.core.tree_walker import TreeNode


def export_element_to_rf_keyword(info: ElementInfo) -> str:
    """
    Generate a Robot Framework keyword call for this element.

    Example output:
        ${element}=    Get Element    path:1|3|2|1
        # Alt: Get Element    id:myButton and type:Button
    """
    locator = best_locator(info)
    strategies = build_locator_strategies(info)

    lines = []
    lines.append(f"${{element}}=    Get Element    {locator}")

    # Add alternative locators as comments
    for s in strategies[1:3]:  # show up to 2 alternatives
        lines.append(f"# Alt: Get Element    {s['locator']}")

    # Add element info as comment
    if info.name:
        lines.append(f"# Name: {info.name}")
    if info.control_type_name:
        lines.append(f"# Type: {info.control_type_name}")
    if info.bounding_rect != (0, 0, 0, 0):
        lines.append(f"# BoundingRect: {info.bounding_rect}")
    if info.center_x or info.center_y:
        lines.append(f"# Center: ({info.center_x}, {info.center_y})")

    return "\n".join(lines)


def export_element_to_variable(info: ElementInfo, var_prefix: str = "LOCATOR") -> str:
    """
    Generate a Robot Framework variable definition for this element.

    Example:
        ${LOCATOR_SAVE_BUTTON}    id:btnSave and type:Button
    """
    # Build a variable name from the element's properties
    name_part = ""
    if info.automation_id:
        name_part = info.automation_id.upper()
    elif info.name:
        name_part = info.name.upper().replace(" ", "_")[:30]
    elif info.control_type_name:
        name_part = info.control_type_name.upper()
    else:
        # Use path indices
        name_part = info.path.replace("path:", "").replace("|", "_")

    # Sanitize variable name
    name_part = "".join(c if c.isalnum() or c == "_" else "_" for c in name_part)
    name_part = name_part.strip("_")

    locator = best_locator(info)
    return f"${{{var_prefix}_{name_part}}}    {locator}"


def export_element_locators(nodes: list["TreeNode"]) -> list[str]:
    """
    Export locator information for a list of tree nodes.
    Produces a Robot Framework .robot file section.

    Args:
        nodes: List of TreeNode objects to export.

    Returns:
        List of lines forming a .robot file section.
    """
    lines = []
    lines.append("*** Comments ***")
    lines.append("# Auto-generated by UIATools Element Inspector")
    lines.append(f"# Total elements: {len(nodes)}")
    lines.append("")

    # Variables section
    lines.append("*** Variables ***")
    for node in nodes:
        info = node.element_info
        # Skip elements without useful identifiers
        if not info.automation_id and not info.name:
            continue
        lines.append(export_element_to_variable(info))
    lines.append("")

    # Documentation section with all element details
    lines.append("*** Comments ***")
    lines.append("# Element Details:")
    lines.append(f"# {'Path':<30} {'Type':<20} {'Name':<40} {'AutomationId':<30} {'BoundingRect'}")
    lines.append(f"# {'-'*30} {'-'*20} {'-'*40} {'-'*30} {'-'*30}")

    for node in nodes:
        info = node.element_info
        indent = "  " * node.depth
        name_display = (info.name[:37] + "...") if len(info.name) > 40 else info.name
        lines.append(
            f"# {indent}{info.path:<30} {info.control_type_name:<20} "
            f"{name_display:<40} {info.automation_id:<30} {info.bounding_rect}"
        )

    return lines


def generate_rf_test_template(info: ElementInfo, action: str = "click") -> str:
    """
    Generate a complete RF test case snippet for an element.

    Args:
        info: Element info.
        action: The action to perform ('click', 'type', 'get_text').

    Returns:
        A Robot Framework test case snippet.
    """
    locator = best_locator(info)
    lines = []
    lines.append("*** Settings ***")
    lines.append("Library    RPA.Windows")
    lines.append("")
    lines.append("*** Test Cases ***")
    lines.append(f"Interact With {info.control_type_name or 'Element'}")

    if action == "click":
        lines.append(f"    Click    {locator}")
    elif action == "type":
        lines.append(f"    ${{element}}=    Get Element    {locator}")
        lines.append(f"    Set Value    ${{element}}    your_text_here")
    elif action == "get_text":
        lines.append(f"    ${{element}}=    Get Element    {locator}")
        lines.append(f"    ${{text}}=    Get Attribute    ${{element}}    Name")
        lines.append(f"    Log    Element text: ${{text}}")
    else:
        lines.append(f"    ${{element}}=    Get Element    {locator}")

    lines.append(f"    # Path: {info.path}")
    lines.append(f"    # Center: ({info.center_x}, {info.center_y})")

    return "\n".join(lines)


def export_elements_to_csv(nodes: list["TreeNode"]) -> str:
    """
    Export element properties to CSV format.

    Exports: Path, AutomationId, Name, ClassName, ControlType

    Args:
        nodes: List of TreeNode objects to export.

    Returns:
        CSV-formatted string with header and all elements.
    """
    import csv
    import io

    output = io.StringIO(newline='')
    writer = csv.writer(output, quoting=csv.QUOTE_ALL, lineterminator='\n')

    # Write header
    writer.writerow(["Path", "AutomationId", "Name", "ClassName", "ControlType"])

    # Write each element
    for node in nodes:
        info = node.element_info
        writer.writerow([
            info.path,
            info.automation_id,
            info.name,
            info.class_name,
            info.control_type_name,
        ])

    return output.getvalue()
